"""
load_and_visualize_amtrak.py - generated by Claude Sonnet 4.5

Downloads the Amtrak GTFS feed and visualizes the multi-stretch
rail network as a graph, ready for Lagrangian relaxation extension.

Dependencies:
    pip install pandas matplotlib networkx requests gtfs-kit
"""

import os
import zipfile, io, urllib.request
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

# ── 1. LOAD GTFS ──────────────────────────────────────────────────────────────

GTFS_URL = "https://transitfeeds.com/p/amtrak/1077/latest/download"
# Fallback: manually download from https://mobilitydatabase.org and set path:

def load_gtfs():
    '''Load GTFS data from local folder'''
    gtfs_path = "gtfs"
    stops = pd.read_csv(os.path.join(gtfs_path, "stops.txt"))
    routes = pd.read_csv(os.path.join(gtfs_path, "routes.txt"))
    trips = pd.read_csv(os.path.join(gtfs_path, "trips.txt"))
    stop_times = pd.read_csv(os.path.join(gtfs_path, "stop_times.txt"))

    return stops, routes, trips, stop_times



# ── 2. BUILD ROUTE→STOP SEQUENCE GRAPH ────────────────────────────────────────
def build_network(stops: pd.DataFrame, routes: pd.DataFrame, trips: pd.DataFrame, stop_times: pd.DataFrame) -> nx.DiGraph:
    '''
    Build directed graph of stations and route segments
    Arguments:
        - stops (pd.DataFrame): GTFS stops.txt with columns stop_id, stop_name, stop_lat, stop_lon
        - routes (pd.DataFrame): GTFS routes.txt with columns route_id, route_short_name, route_long_name
        - trips (pd.DataFrame): GTFS trips.txt with columns trip_id, route_id, trip_headsign
        - stop_times (pd.DataFrame): GTFS stop_times.txt with columns trip_id, stop_id, stop_sequence
    Returns:
        - G (nx.DiGraph): directed graph where nodes are stations and edges represent consecutive stops on a trip, with attributes for route overlap
    '''
    # Merge trips → routes → stop_times → stops
    st = stop_times.merge(trips[["trip_id","route_id","trip_headsign"]], on="trip_id")
    st = st.merge(stops[["stop_id","stop_name","stop_lat","stop_lon"]], on="stop_id")
    st["stop_sequence"] = st["stop_sequence"].astype(int)
    st = st.sort_values(["trip_id", "stop_sequence"])

    # Build directed graph: edges are consecutive station pairs on a trip
    G = nx.DiGraph()

    # Add station nodes
    for _, row in stops.iterrows():
        G.add_node(row["stop_id"],
                name=row["stop_name"],
                lat=float(row["stop_lat"]),
                lon=float(row["stop_lon"]))

    # Add edges (one per consecutive stop-pair per route; deduplicated)
    edge_routes = {}   # (u,v) → set of route_ids
    for trip_id, grp in st.groupby("trip_id"):
        grp = grp.sort_values("stop_sequence")
        route_id = grp.iloc[0]["route_id"]
        pairs = list(zip(grp["stop_id"].tolist(), grp["stop_id"].tolist()[1:]))
        for u, v in pairs:
            key = (u, v)
            edge_routes.setdefault(key, set()).add(route_id)

    for (u, v), rids in edge_routes.items():
        G.add_edge(u, v, routes=rids, n_routes=len(rids))
    

    print(f"Graph: {G.number_of_nodes()} stations, {G.number_of_edges()} directed edges")

    return G

# ── 4. VISUALIZE ──────────────────────────────────────────────────────────────
def visualize_network(G: nx.DiGraph) -> None:

    # ── 3. IDENTIFY MULTI-STRETCH JUNCTIONS ───────────────────────────────────────
    # A junction is a node with degree > 2 in the undirected sense — where
    # multiple lines diverge, exactly analogous to where single-track stretches
    # in the paper would need coupling/coordination constraints.

    UG = G.to_undirected()
    junctions = [n for n in UG.nodes if UG.degree(n) > 2]
    print(f"Network junctions (branching stations): {len(junctions)}")
    for j in junctions[:10]:
        print(f"  {G.nodes[j]['name']}  (degree {UG.degree(j)})")

    fig, axes = plt.subplots(1, 2, figsize=(18, 8))
    fig.suptitle("Amtrak Rail Network — Multi-Stretch Graph", fontsize=14, fontweight="bold")

    # Geographic layout (lon, lat)
    pos = {n: (float(G.nodes[n]["lon"]), float(G.nodes[n]["lat"]))
        for n in G.nodes}

    def format_station_label(node_id: str) -> str:
        name = G.nodes[node_id]["name"].split("/")[0].strip()
        return f"{name} ({node_id})"

    def apply_plot_padding(ax, positions, x_pad: float = 0.08, y_pad: float = 0.08) -> None:
        xs = [x for x, _ in positions.values()]
        ys = [y for _, y in positions.values()]
        if not xs or not ys:
            return
        x_min, x_max = min(xs), max(xs)
        y_min, y_max = min(ys), max(ys)
        x_margin = max((x_max - x_min) * x_pad, 0.15)
        y_margin = max((y_max - y_min) * y_pad, 0.15)
        ax.set_xlim(x_min - x_margin, x_max + x_margin)
        ax.set_ylim(y_min - y_margin, y_max + y_margin)

    # ── Panel A: full network ──
    ax = axes[0]
    ax.set_title("Full Network (geographic)", fontsize=11)
    ax.set_facecolor("#f0f0f0")

    # colour edges by number of overlapping routes (proxy for track contention)
    edge_list = list(G.edges())
    weights   = [G[u][v]["n_routes"] for u, v in edge_list]
    max_w     = max(weights) if weights else 1

    # Draw edges: single line for shared tracks, slight curve offset for bidirectional pairs
    for (u, v), n_rts in zip(edge_list, weights):
        # Color intensity increases with number of routes on this segment
        color = cm.plasma(min(n_rts / max_w, 1.0))
        width = 1.2 + (n_rts - 1) * 0.3  # Thicker lines for more routes
        
        # Check if reverse edge exists (bidirectional track)
        reverse_exists = G.has_edge(v, u)
        rad = 0.08 if reverse_exists else 0.0  # Slight curve if bidirectional
        
        nx.draw_networkx_edges(G, pos, edgelist=[(u, v)],
                            edge_color=[color],
                            width=width, arrows=False, alpha=0.7, ax=ax,
                            connectionstyle=f"arc3,rad={rad}")
        
        # Add label for multi-route segments
        if n_rts > 1:
            x = (pos[u][0] + pos[v][0]) / 2
            y = (pos[u][1] + pos[v][1]) / 2
            ax.text(x, y, f"×{n_rts}", fontsize=5, ha="center", va="center",
                   bbox=dict(boxstyle="round,pad=0.2", facecolor="white", alpha=0.7, edgecolor="gray"))
    nx.draw_networkx_nodes(G, pos,
        nodelist=[n for n in G.nodes if n not in junctions],
        node_size=15, node_color="#2196F3", alpha=0.7, ax=ax)
    nx.draw_networkx_nodes(G, pos,
        nodelist=junctions,
        node_size=60, node_color="#FF5722", alpha=0.9, ax=ax)

    # Label junctions only
    junction_labels = {n: format_station_label(n) for n in junctions}
    nx.draw_networkx_labels(G, pos, labels=junction_labels,
                            font_size=5.5, font_color="#111", ax=ax, clip_on=False)

    apply_plot_padding(ax, pos)

    ax.set_xlabel("Longitude"); ax.set_ylabel("Latitude")
    sm = plt.cm.ScalarMappable(cmap=cm.plasma,
        norm=plt.Normalize(vmin=1, vmax=max_w))
    sm.set_array([])
    plt.colorbar(sm, ax=ax, shrink=0.6, label="Overlapping routes on segment")

    # ── Panel B: Northeast Corridor subgraph (most congested stretch) ──
    ax2 = axes[1]
    ax2.set_title("Northeast Corridor Sub-network\n(highest contention — key for multi-stretch ILP)", fontsize=11)
    ax2.set_facecolor("#f0f0f0")

    # Filter to rough NEC bounding box
    NEC_BBOX = dict(lat_min=38.5, lat_max=42.5, lon_min=-75.5, lon_max=-70.5)
    nec_nodes = [n for n in G.nodes
                if NEC_BBOX["lat_min"] < float(G.nodes[n]["lat"]) < NEC_BBOX["lat_max"]
                and NEC_BBOX["lon_min"] < float(G.nodes[n]["lon"]) < NEC_BBOX["lon_max"]]
    SG = G.subgraph(nec_nodes)

    pos_nec = {n: (float(G.nodes[n]["lon"]), float(G.nodes[n]["lat"])) for n in SG.nodes}
    junc_nec = [n for n in SG.nodes if UG.degree(n) > 2]

    e_nec   = list(SG.edges())
    w_nec   = [SG[u][v]["n_routes"] for u, v in e_nec]

    # Draw edges: single line for shared tracks, curve offset for bidirectional pairs
    for (u, v), n_rts in zip(e_nec, w_nec):
        # Color intensity increases with number of routes on this segment
        color = cm.plasma(min(n_rts / max_w, 1.0))
        width = 2.2 + (n_rts - 1) * 0.5  # Thicker lines for more routes
        
        # Check if reverse edge exists (bidirectional track)
        reverse_exists = SG.has_edge(v, u)
        rad = 0.12 if reverse_exists else 0.0  # More noticeable curve if bidirectional
        
        nx.draw_networkx_edges(SG, pos_nec, edgelist=[(u, v)],
                            edge_color=[color],
                            width=width, arrows=True, arrowsize=8, alpha=0.85, ax=ax2,
                            connectionstyle=f"arc3,rad={rad}")
        
        # Add label for multi-route segments
        if n_rts > 1:
            x = (pos_nec[u][0] + pos_nec[v][0]) / 2
            y = (pos_nec[u][1] + pos_nec[v][1]) / 2
            ax2.text(x, y, f"×{n_rts}", fontsize=7, ha="center", va="center",
                    bbox=dict(boxstyle="round,pad=0.3", facecolor="yellow", alpha=0.7, edgecolor="orange"))
    nx.draw_networkx_nodes(SG, pos_nec,
        nodelist=[n for n in SG.nodes if n not in junc_nec],
        node_size=40, node_color="#2196F3", alpha=0.8, ax=ax2)
    nx.draw_networkx_nodes(SG, pos_nec,
        nodelist=junc_nec, node_size=120, node_color="#FF5722", alpha=0.95, ax=ax2)

    nec_labels = {n: format_station_label(n) for n in SG.nodes}
    nx.draw_networkx_labels(SG, pos_nec, labels=nec_labels,
                            font_size=6, font_color="#111", ax=ax2, clip_on=False)

    apply_plot_padding(ax2, pos_nec)
    ax2.set_xlabel("Longitude"); ax2.set_ylabel("Latitude")

    plt.tight_layout()
    plt.savefig("amtrak_network.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("Saved amtrak_network.png")

    # ── 5. PRINT ILP-RELEVANT SUMMARY ────────────────────────────────────────────

    n_routes   = routes["route_id"].nunique()
    n_trips    = trips["trip_id"].nunique()
    n_stations = stops["stop_id"].nunique()
    n_shared   = sum(1 for (u,v) in G.edges if G[u][v]["n_routes"] > 1)

    print("\n── ILP Problem Size Indicators ──────────────────────────────")
    print(f"  Routes (train services):   {n_routes}")
    print(f"  Trips (individual runs):   {n_trips}")
    print(f"  Stations (nodes):          {n_stations}")
    print(f"  Shared-track edge pairs:   {n_shared}  ← these need capacity constraints")
    print(f"  Junction stations:         {len(junctions)}  ← Lagrange coupling points")